services:
  syn-gestao:
    image: ghcr.io/synribeiro/syn-gestao:latest
    ports:
      - "8088:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
